# -*- coding: utf-8 -*-
"""SAM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11iKsRGu0jW5Ib-DNEnyyS_YKYMnn9gzL

# Dynamics of Transformers in LLMs

## Aim
To study how token representations evolve across transformer layers using:
1. ODE-based simulation of self-attention
2. Empirical validation using GPT-2

We analyze:
- Consensus (collapse)
- Clustering
- Neural Stiffness

##SECTION 1 — Setup
"""

import numpy as np
import matplotlib.pyplot as plt

"""##SECTION 2 — Initialize Tokens on Sphere"""

n_tokens = 10
dim = 3

X0 = np.random.randn(n_tokens, dim)
X0 = X0 / np.linalg.norm(X0, axis=1, keepdims=True)

"""##SECTION 3 — Attention Function"""

def attention(X):
    scores = X @ X.T
    exp_scores = np.exp(scores)
    A = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
    return A

"""##SECTION 4 — ODE Dynamics (CORE)"""

def step(X, V, dt=0.1):
    A = attention(X)
    X_new = np.zeros_like(X)

    for i in range(len(X)):
        interaction = np.sum(A[i][:, None] * (V @ X.T).T, axis=0)

        proj = interaction - np.dot(X[i], interaction) * X[i]
        X_new[i] = X[i] + dt * proj

    return X_new / np.linalg.norm(X_new, axis=1, keepdims=True)

"""##SECTION 5 — Run Simulation"""

V1 = np.eye(dim)
X = X0.copy()

traj1 = []
for _ in range(100):
    X = step(X, V1)
    traj1.append(X.copy())

V2 = np.array([[1,0,0],
               [0,-1,0],
               [0,0,0.5]])

X = X0.copy()
traj2 = []

for _ in range(100):
    X = step(X, V2)
    traj2.append(X.copy())

"""##SECTION 6 — Measure Collapse (VERY IMPORTANT)"""

def avg_distance(X):
    n = X.shape[0]
    return np.mean([np.linalg.norm(X[i]-X[j]) for i in range(n) for j in range(n)])

def avg_cosine(X):
    n = X.shape[0]
    return np.mean([np.dot(X[i], X[j]) for i in range(n) for j in range(n)])

"""##SECTION 7 — Neural Stiffness Index"""

def compute_nsi(traj):
    nsi = []
    for t in range(len(traj)-1):
        nsi.append(np.linalg.norm(traj[t+1]-traj[t]) /
                   (np.linalg.norm(traj[t]) + 1e-8))
    return nsi

dist1 = [avg_distance(x) for x in traj1]
dist2 = [avg_distance(x) for x in traj2]

plt.plot(dist1, label="Collapse")
plt.plot(dist2, label="Clustering")
plt.legend()
plt.title("Token Distance Dynamics")
plt.show()

"""##SECTION 8"""

from transformers import GPT2Model, GPT2Tokenizer
import torch

model = GPT2Model.from_pretrained("gpt2")
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

text = "Transformers are powerful models"
inputs = tokenizer(text, return_tensors="pt")

outputs = model(**inputs, output_hidden_states=True)
hidden_states = outputs.hidden_states

layer_dist = []
for layer in hidden_states:
    X = layer[0].detach().numpy()
    layer_dist.append(avg_distance(X))

plt.plot(layer_dist)
plt.title("GPT-2 Token Dynamics")
plt.show()

"""The simulation results show that token distances decrease over layers, indicating convergence to a consensus state. This behavior arises due to the averaging effect of attention when the value matrix is identity.

In contrast, GPT-2 exhibits an initial increase in token distances followed by a gradual decrease. This suggests that real transformers first expand feature representations and then compress them in deeper layers.

The Neural Stiffness Index highlights layers where significant representation changes occur, indicating that only a subset of layers contribute strongly to transformation.

When a non-identity value matrix is used, the system exhibits clustering behavior instead of full collapse, demonstrating multistability. This aligns with theoretical predictions of multiple equilibrium states in attention dynamics.

“We modeled transformer layers as a dynamical system using an ODE formulation of self-attention. We observed that tokens converge to a consensus state due to repeated averaging. We validated this behavior using GPT-2 hidden states, which showed similar but more complex dynamics. Additionally, we demonstrated clustering behavior under different value matrices, confirming multistability.”
"""